backend:
  name: github
  repo: dileepkr1996c-arch/You-Grow-Online
  branch: main
  use_device_flow: true

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Robots Settings", name: "robots", widget: "hidden", default: "index, follow" }
      - { label: "Blog Title (H1)", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image (Thumbnail)", name: "image", widget: "image" }
      - { label: "Short Description (Meta Description)", name: "description", widget: "text" }
      - { label: "Custom SEO Title (Optional)", name: "meta_title", widget: "string", required: false }
      - { label: "Keywords (Optional)", name: "keywords", widget: "string", required: false }
      - { label: "Author Name (Optional)", name: "author", widget: "string", required: false, default: "You Grow Online" }
      - { label: "Blog Body Content", name: "body", widget: "markdown" }
